/*
 Nick Soetaert
 October 11, 2018
*/

public enum Property {
    BALTIC_AVE, MEDITERRANEAN_AVE, 	//BROWN
    BOARDWALK, PARK_PLACE,		//BLUE
    NORTH_CAROLINA_AVE, PACIFIC_AVE, PENNSYLVANIA_AVE, //GREEN
    CONNECTICUT_AVE, ORIENTAL_AVE, VERMONT_AVE, //LIGHT_BLUE
    NEW_YORK_AVE, ST_JAMES_PLACE, TENNESSE_AVE, //ORANGE
    ST_CHARLES_PLACE, VIRGINIA_AVE, STATES_AVE, //PINK
    KENTUCKY_AVE, INDIANA_AVE, ILLINOIS_AVE,	//RED
    VENTNOR_AVE, MARVIN_GARDENS, ATLANTIC_AVE,	//YELLOW
    SHORT_LINE, BO_RAIL, READING_RAIL, PENNSYLVANIA_RAIL, //RAIL
    WATER_WORKS, ELECTRIC_CO	//UTILITY
}
